services:
  postgres: 
    image: soljahd/music-library-db
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: music_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/lib/postgresql/pg_log
    networks:
      - music_network
    restart: unless-stopped
    command: >
      -p ${DB_PORT}
      -c logging_collector=on
      -c log_directory='/var/lib/postgresql/pg_log'
      -c log_filename='postgresql-%Y-%m-%d_%H%M%S.log'
      -c log_statement='all'
      -c log_connections=on
      -c log_disconnections=on
      -c log_hostname=on

  app:
    image: soljahd/music-library-app
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: music_app
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    networks:
      - music_network
    restart: unless-stopped

networks:
  music_network:
    driver: bridge
    name: music_network

volumes:
  postgres_data:
  postgres_logs:
